---
engines:
  duplication:
    enabled: true
    config:
      languages:
        javascript:
          mass_threshold: 60
  tslint:
    enabled: true
  fixme:
    enabled: true
ratings:
  paths:
  - "**.ts"
  - "**.scss"
  - "**.pug"
exclude_paths:
- dist/